title : My Résumé... and a few notes.

baseurl: /bodey-cv
safe: true
lsi: false
pygments: true

author :
  name : Bodey Baker
  email : bodey.baker@gmail.com
  github : porcoesphino
  twitter : porcoesphino
